"""Change user preferences to JSON type

Revision ID: 53b98528d949
Revises: ee736fc43484
Create Date: 2025-07-09 20:21:12.558247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b98528d949'
down_revision: Union[str, None] = 'ee736fc43484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_is_user_message'), 'chat_messages', ['is_user_message'], unique=False)
    op.create_index('ix_chat_messages_page_created', 'chat_messages', ['page_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_page_id'), 'chat_messages', ['page_id'], unique=False)
    op.create_index('ix_chat_messages_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_index('ix_chat_messages_user_page_created', 'chat_messages', ['user_id', 'page_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pages_created_at'), 'pages', ['created_at'], unique=False)
    op.create_index(op.f('ix_pages_last_opened_at'), 'pages', ['last_opened_at'], unique=False)
    op.create_index('ix_pages_user_created', 'pages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pages_user_id'), 'pages', ['user_id'], unique=False)
    op.create_index('ix_pages_user_last_opened', 'pages', ['user_id', 'last_opened_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pages_user_last_opened', table_name='pages')
    op.drop_index(op.f('ix_pages_user_id'), table_name='pages')
    op.drop_index('ix_pages_user_created', table_name='pages')
    op.drop_index(op.f('ix_pages_last_opened_at'), table_name='pages')
    op.drop_index(op.f('ix_pages_created_at'), table_name='pages')
    op.drop_index('ix_chat_messages_user_page_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_user_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_page_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_page_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_is_user_message'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    # ### end Alembic commands ###
