"""Add created_at to ChatMessage

Revision ID: 56bf93be7291
Revises: 7791c3b05b74
Create Date: 2025-06-11 15:27:01.316428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56bf93be7291'
down_revision: Union[str, None] = '7791c3b05b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('chat_messages', sa.Column('is_user_message', sa.Boolean(), nullable=False))
    op.add_column('chat_messages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('chat_messages', 'timestamp')
    op.drop_column('chat_messages', 'role')
    op.drop_column('chat_messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('chat_messages', 'created_at')
    op.drop_column('chat_messages', 'is_user_message')
    op.drop_column('chat_messages', 'message')
    # ### end Alembic commands ###
