"""Add is_error to chat_messages

Revision ID: 5e8b6b3e3e3e
Revises: dd1c6d3e3b4a
Create Date: 2024-07-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8b6b3e3e3e'
down_revision = 'dd1c6d3e3b4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_error', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_error')
    # ### end Alembic commands ### 