"""Finalize features and fix models

Revision ID: c23b2bb6e2a3
Revises: abf8887c03b6
Create Date: 2025-06-11 13:17:35.955699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23b2bb6e2a3'
down_revision: Union[str, None] = 'abf8887c03b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_cover_letters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_cvs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.alter_column('applications', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'job_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'active')
    op.drop_column('users', 'picture')
    op.drop_column('users', 'external_id')
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'job_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('generated_cvs')
    op.drop_table('generated_cover_letters')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
