"""Add last_opened_at to pages table

Revision ID: ee736fc43484
Revises: enhanced_memory_001
Create Date: 2025-07-03 03:39:03.353916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee736fc43484'
down_revision: Union[str, None] = 'enhanced_memory_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('last_opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('user_behaviors', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('idx_user_behaviors_action_type'), table_name='user_behaviors')
    op.drop_index(op.f('idx_user_behaviors_created_at'), table_name='user_behaviors')
    op.drop_index(op.f('idx_user_behaviors_user_id'), table_name='user_behaviors')
    op.drop_index(op.f('idx_user_preferences_key'), table_name='user_preferences')
    op.drop_index(op.f('idx_user_preferences_user_id'), table_name='user_preferences')
    op.drop_constraint(op.f('unique_user_preference'), 'user_preferences', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_user_preference'), 'user_preferences', ['user_id', 'preference_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_preferences_key'), 'user_preferences', ['preference_key'], unique=False)
    op.create_index(op.f('idx_user_behaviors_user_id'), 'user_behaviors', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_behaviors_created_at'), 'user_behaviors', ['created_at'], unique=False)
    op.create_index(op.f('idx_user_behaviors_action_type'), 'user_behaviors', ['action_type'], unique=False)
    op.alter_column('user_behaviors', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('pages', 'last_opened_at')
    # ### end Alembic commands ###
